services:
  web_api:
    image: zenithhelios/demowebapi_2
    container_name: web_api
    environment:
      - DB_HOST=mssql_server
      - DB_PORT=1433
      - DB_NAME=MotelManagement2024DB
      - DB_SA_PASSWORD=myPassw0rd
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mssql_server

  mssql_server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=myPassw0rd
    ports:
      - "1433:1433"
